import { MigrationInterface, QueryRunner } from "typeorm";

export class AddedRdvType1746275433413 implements MigrationInterface {
    name = 'AddedRdvType1746275433413'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`utilisateur\` DROP FOREIGN KEY \`FK_1f5e23f7f31776c71c71195e69f\``);
        await queryRunner.query(`ALTER TABLE \`utilisateur\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`utilisateur\` CHANGE \`telephone\` \`telephone\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`utilisateur\` CHANGE \`adresse\` \`adresse\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`utilisateur\` CHANGE \`twoFactorSecret\` \`twoFactorSecret\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`utilisateur\` CHANGE \`lastLogin\` \`lastLogin\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`utilisateur\` CHANGE \`verificationToken\` \`verificationToken\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`utilisateur\` CHANGE \`verificationExpires\` \`verificationExpires\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`utilisateur\` CHANGE \`numLicence\` \`numLicence\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`utilisateur\` CHANGE \`specialites\` \`specialites\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`utilisateur\` CHANGE \`cliniqueId\` \`cliniqueId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`clinique\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`clinique\` CHANGE \`coordonneesGPS\` \`coordonneesGPS\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`disponibilite\` DROP FOREIGN KEY \`FK_7bc363a2aee1cb987005fe84c5b\``);
        await queryRunner.query(`ALTER TABLE \`disponibilite\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`disponibilite\` CHANGE \`dateExceptionnelle\` \`dateExceptionnelle\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`disponibilite\` CHANGE \`veterinaire_id\` \`veterinaire_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`dossier_medical\` DROP FOREIGN KEY \`FK_00a91c89fd584b0a770b67c5879\``);
        await queryRunner.query(`ALTER TABLE \`dossier_medical\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`dossier_medical\` CHANGE \`observations\` \`observations\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`dossier_medical\` CHANGE \`antecedants\` \`antecedants\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`dossier_medical\` CHANGE \`allergies\` \`allergies\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`dossier_medical\` CHANGE \`animalId\` \`animalId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`consultation\` DROP FOREIGN KEY \`FK_81707cee496700b3d69c67fb91c\``);
        await queryRunner.query(`ALTER TABLE \`consultation\` DROP FOREIGN KEY \`FK_d96e3869e0b41ebb2e9a84fe20b\``);
        await queryRunner.query(`ALTER TABLE \`consultation\` DROP FOREIGN KEY \`FK_d5f9e8c8d70c8f51c57aa5c0ec2\``);
        await queryRunner.query(`ALTER TABLE \`consultation\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`consultation\` CHANGE \`dateConsultation\` \`dateConsultation\` timestamp NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`consultation\` CHANGE \`diagnostic\` \`diagnostic\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`consultation\` CHANGE \`traitement\` \`traitement\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`consultation\` CHANGE \`notes\` \`notes\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`consultation\` CHANGE \`lien\` \`lien\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`consultation\` CHANGE \`contenu\` \`contenu\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`consultation\` CHANGE \`typeAppel\` \`typeAppel\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`consultation\` CHANGE \`enregistrementURL\` \`enregistrementURL\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`consultation\` CHANGE \`animalId\` \`animalId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`consultation\` CHANGE \`rendezvousId\` \`rendezvousId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`consultation\` CHANGE \`veterinaireId\` \`veterinaireId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`animal\` DROP FOREIGN KEY \`FK_ea0cfb88c0ae9531a44fedb98c4\``);
        await queryRunner.query(`ALTER TABLE \`animal\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`animal\` CHANGE \`proprietaireId\` \`proprietaireId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`rendezvous_animaux\` DROP FOREIGN KEY \`FK_245a088537113ca38b284656bce\``);
        await queryRunner.query(`ALTER TABLE \`rendezvous_animaux\` DROP FOREIGN KEY \`FK_77d9414456ca95dc12e05c2f401\``);
        await queryRunner.query(`ALTER TABLE \`rendezvous_animaux\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`rendezvous_animaux\` CHANGE \`rendezvous_id\` \`rendezvous_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`rendezvous_animaux\` CHANGE \`animal_id\` \`animal_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`rendezvous\` DROP FOREIGN KEY \`FK_fc5fd26981a9e5c9f8c8c494814\``);
        await queryRunner.query(`ALTER TABLE \`rendezvous\` DROP FOREIGN KEY \`FK_173ee5bc6714dcc6aa0a4bd5a08\``);
        await queryRunner.query(`ALTER TABLE \`rendezvous\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`rendezvous\` CHANGE \`motif\` \`motif\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`rendezvous\` DROP COLUMN \`statut\``);
        await queryRunner.query(`ALTER TABLE \`rendezvous\` ADD \`statut\` enum ('pending', 'confirmed', 'canceled', 'completed') NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`rendezvous\` CHANGE \`notes\` \`notes\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`rendezvous\` CHANGE \`veterinaire_id\` \`veterinaire_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`rendezvous\` CHANGE \`proprietaire_id\` \`proprietaire_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`fiche_medicale\` CHANGE \`notes\` \`notes\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`password_reset\` DROP FOREIGN KEY \`FK_ad88301fdc79593dd222268a8b6\``);
        await queryRunner.query(`ALTER TABLE \`password_reset\` CHANGE \`user_id\` \`user_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`utilisateur\` ADD CONSTRAINT \`FK_1f5e23f7f31776c71c71195e69f\` FOREIGN KEY (\`cliniqueId\`) REFERENCES \`clinique\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`disponibilite\` ADD CONSTRAINT \`FK_7bc363a2aee1cb987005fe84c5b\` FOREIGN KEY (\`veterinaire_id\`) REFERENCES \`utilisateur\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`dossier_medical\` ADD CONSTRAINT \`FK_00a91c89fd584b0a770b67c5879\` FOREIGN KEY (\`animalId\`) REFERENCES \`animal\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`consultation\` ADD CONSTRAINT \`FK_81707cee496700b3d69c67fb91c\` FOREIGN KEY (\`animalId\`) REFERENCES \`animal\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`consultation\` ADD CONSTRAINT \`FK_d96e3869e0b41ebb2e9a84fe20b\` FOREIGN KEY (\`rendezvousId\`) REFERENCES \`rendezvous\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`consultation\` ADD CONSTRAINT \`FK_d5f9e8c8d70c8f51c57aa5c0ec2\` FOREIGN KEY (\`veterinaireId\`) REFERENCES \`utilisateur\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`animal\` ADD CONSTRAINT \`FK_ea0cfb88c0ae9531a44fedb98c4\` FOREIGN KEY (\`proprietaireId\`) REFERENCES \`utilisateur\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rendezvous_animaux\` ADD CONSTRAINT \`FK_245a088537113ca38b284656bce\` FOREIGN KEY (\`rendezvous_id\`) REFERENCES \`rendezvous\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rendezvous_animaux\` ADD CONSTRAINT \`FK_77d9414456ca95dc12e05c2f401\` FOREIGN KEY (\`animal_id\`) REFERENCES \`animal\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rendezvous\` ADD CONSTRAINT \`FK_fc5fd26981a9e5c9f8c8c494814\` FOREIGN KEY (\`veterinaire_id\`) REFERENCES \`utilisateur\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rendezvous\` ADD CONSTRAINT \`FK_173ee5bc6714dcc6aa0a4bd5a08\` FOREIGN KEY (\`proprietaire_id\`) REFERENCES \`utilisateur\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`password_reset\` ADD CONSTRAINT \`FK_ad88301fdc79593dd222268a8b6\` FOREIGN KEY (\`user_id\`) REFERENCES \`utilisateur\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`password_reset\` DROP FOREIGN KEY \`FK_ad88301fdc79593dd222268a8b6\``);
        await queryRunner.query(`ALTER TABLE \`rendezvous\` DROP FOREIGN KEY \`FK_173ee5bc6714dcc6aa0a4bd5a08\``);
        await queryRunner.query(`ALTER TABLE \`rendezvous\` DROP FOREIGN KEY \`FK_fc5fd26981a9e5c9f8c8c494814\``);
        await queryRunner.query(`ALTER TABLE \`rendezvous_animaux\` DROP FOREIGN KEY \`FK_77d9414456ca95dc12e05c2f401\``);
        await queryRunner.query(`ALTER TABLE \`rendezvous_animaux\` DROP FOREIGN KEY \`FK_245a088537113ca38b284656bce\``);
        await queryRunner.query(`ALTER TABLE \`animal\` DROP FOREIGN KEY \`FK_ea0cfb88c0ae9531a44fedb98c4\``);
        await queryRunner.query(`ALTER TABLE \`consultation\` DROP FOREIGN KEY \`FK_d5f9e8c8d70c8f51c57aa5c0ec2\``);
        await queryRunner.query(`ALTER TABLE \`consultation\` DROP FOREIGN KEY \`FK_d96e3869e0b41ebb2e9a84fe20b\``);
        await queryRunner.query(`ALTER TABLE \`consultation\` DROP FOREIGN KEY \`FK_81707cee496700b3d69c67fb91c\``);
        await queryRunner.query(`ALTER TABLE \`dossier_medical\` DROP FOREIGN KEY \`FK_00a91c89fd584b0a770b67c5879\``);
        await queryRunner.query(`ALTER TABLE \`disponibilite\` DROP FOREIGN KEY \`FK_7bc363a2aee1cb987005fe84c5b\``);
        await queryRunner.query(`ALTER TABLE \`utilisateur\` DROP FOREIGN KEY \`FK_1f5e23f7f31776c71c71195e69f\``);
        await queryRunner.query(`ALTER TABLE \`password_reset\` CHANGE \`user_id\` \`user_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`password_reset\` ADD CONSTRAINT \`FK_ad88301fdc79593dd222268a8b6\` FOREIGN KEY (\`user_id\`) REFERENCES \`utilisateur\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fiche_medicale\` CHANGE \`notes\` \`notes\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rendezvous\` CHANGE \`proprietaire_id\` \`proprietaire_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rendezvous\` CHANGE \`veterinaire_id\` \`veterinaire_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rendezvous\` CHANGE \`notes\` \`notes\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rendezvous\` DROP COLUMN \`statut\``);
        await queryRunner.query(`ALTER TABLE \`rendezvous\` ADD \`statut\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`rendezvous\` CHANGE \`motif\` \`motif\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rendezvous\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rendezvous\` ADD CONSTRAINT \`FK_173ee5bc6714dcc6aa0a4bd5a08\` FOREIGN KEY (\`proprietaire_id\`) REFERENCES \`utilisateur\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rendezvous\` ADD CONSTRAINT \`FK_fc5fd26981a9e5c9f8c8c494814\` FOREIGN KEY (\`veterinaire_id\`) REFERENCES \`utilisateur\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rendezvous_animaux\` CHANGE \`animal_id\` \`animal_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rendezvous_animaux\` CHANGE \`rendezvous_id\` \`rendezvous_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rendezvous_animaux\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rendezvous_animaux\` ADD CONSTRAINT \`FK_77d9414456ca95dc12e05c2f401\` FOREIGN KEY (\`animal_id\`) REFERENCES \`animal\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rendezvous_animaux\` ADD CONSTRAINT \`FK_245a088537113ca38b284656bce\` FOREIGN KEY (\`rendezvous_id\`) REFERENCES \`rendezvous\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`animal\` CHANGE \`proprietaireId\` \`proprietaireId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`animal\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`animal\` ADD CONSTRAINT \`FK_ea0cfb88c0ae9531a44fedb98c4\` FOREIGN KEY (\`proprietaireId\`) REFERENCES \`utilisateur\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`consultation\` CHANGE \`veterinaireId\` \`veterinaireId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`consultation\` CHANGE \`rendezvousId\` \`rendezvousId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`consultation\` CHANGE \`animalId\` \`animalId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`consultation\` CHANGE \`enregistrementURL\` \`enregistrementURL\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`consultation\` CHANGE \`typeAppel\` \`typeAppel\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`consultation\` CHANGE \`contenu\` \`contenu\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`consultation\` CHANGE \`lien\` \`lien\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`consultation\` CHANGE \`notes\` \`notes\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`consultation\` CHANGE \`traitement\` \`traitement\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`consultation\` CHANGE \`diagnostic\` \`diagnostic\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`consultation\` CHANGE \`dateConsultation\` \`dateConsultation\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`consultation\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`consultation\` ADD CONSTRAINT \`FK_d5f9e8c8d70c8f51c57aa5c0ec2\` FOREIGN KEY (\`veterinaireId\`) REFERENCES \`utilisateur\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`consultation\` ADD CONSTRAINT \`FK_d96e3869e0b41ebb2e9a84fe20b\` FOREIGN KEY (\`rendezvousId\`) REFERENCES \`rendezvous\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`consultation\` ADD CONSTRAINT \`FK_81707cee496700b3d69c67fb91c\` FOREIGN KEY (\`animalId\`) REFERENCES \`animal\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`dossier_medical\` CHANGE \`animalId\` \`animalId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dossier_medical\` CHANGE \`allergies\` \`allergies\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dossier_medical\` CHANGE \`antecedants\` \`antecedants\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dossier_medical\` CHANGE \`observations\` \`observations\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dossier_medical\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dossier_medical\` ADD CONSTRAINT \`FK_00a91c89fd584b0a770b67c5879\` FOREIGN KEY (\`animalId\`) REFERENCES \`animal\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`disponibilite\` CHANGE \`veterinaire_id\` \`veterinaire_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`disponibilite\` CHANGE \`dateExceptionnelle\` \`dateExceptionnelle\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`disponibilite\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`disponibilite\` ADD CONSTRAINT \`FK_7bc363a2aee1cb987005fe84c5b\` FOREIGN KEY (\`veterinaire_id\`) REFERENCES \`utilisateur\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`clinique\` CHANGE \`coordonneesGPS\` \`coordonneesGPS\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`clinique\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`utilisateur\` CHANGE \`cliniqueId\` \`cliniqueId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`utilisateur\` CHANGE \`specialites\` \`specialites\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`utilisateur\` CHANGE \`numLicence\` \`numLicence\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`utilisateur\` CHANGE \`verificationExpires\` \`verificationExpires\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`utilisateur\` CHANGE \`verificationToken\` \`verificationToken\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`utilisateur\` CHANGE \`lastLogin\` \`lastLogin\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`utilisateur\` CHANGE \`twoFactorSecret\` \`twoFactorSecret\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`utilisateur\` CHANGE \`adresse\` \`adresse\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`utilisateur\` CHANGE \`telephone\` \`telephone\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`utilisateur\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`utilisateur\` ADD CONSTRAINT \`FK_1f5e23f7f31776c71c71195e69f\` FOREIGN KEY (\`cliniqueId\`) REFERENCES \`clinique\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
